# Generated by Django 6.0.5 on 2026-05-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='json_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterModelTable(
            name='solicitud',
            table=None,
        ),
    ]
