# Generated by Django 6.0.5 on 2026-05-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_solicitud_json_data_alter_solicitud_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='mensaje_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='resultado_excel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
