# Generated by Django 4.2.27 on 2026-05-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_add_resultado_excel_mensaje_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('en espera', 'En espera'), ('en proceso', 'En proceso'), ('completado', 'Completado')], max_length=20),
        ),
    ]
