# Generated by Django 6.0.5 on 2026-05-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_solicitud_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
