# Generated by Django 4.2.27 on 2026-05-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('conviviente', 'Conviviente'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=20, null=True),
        ),
    ]
